<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Georgy_Kasymbekov</Authors>
    <Product>Nails</Product>
    <Description>in-memory data storage implementation for DGV project</Description>
    <Version>1.0.0</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
	<PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageIcon>resized-9361.jpg</PackageIcon>
    <PackageId>KGServices</PackageId>
	  <PackageTags>storage;in-memory;repository;services;datagridview;items</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Entities\Entities.csproj" />
    <ProjectReference Include="..\Services.Contacts\Services.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Storage.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

</Project>
